### ISSUE TITLE
cache cost over 5min wait and finally failed in `onSuccess()`

### ISSUE THREAD

**Issue by wuhuizuo** [j3t/jenkins-pipeline-cache-plugin#22]
### My pipeline part
```groovy
stage('Checkout') {
            parallel {   
                stage("repo1") {
                    steps {
                        dir("repo1") {
                            // using plugin: https://github.com/j3t/jenkins-pipeline-cache-plugin
                            cache(path: "./", filter: '**/*', key: "git//repo1-${ghprbActualCommit}", restoreKeys: ['git/repo1-']) {
                                retry(2) {
                                    checkout(
                                        changelog: false,
                                        poll: false,
                                        scm: [
                                            $class: 'GitSCM', branches: [[name: ghprbActualCommit]], 
                                            doGenerateSubmoduleConfigurations: false, 
                                            extensions: [
                                                [$class: 'PruneStaleBranch'],
                                                [$class: 'CleanBeforeCheckout'], 
                                                [$class: 'CloneOption', timeout: 15],
                                            ],
                                            submoduleCfg: [],
                                            userRemoteConfigs: [[
                                                refspec: "+refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*", 
                                                url: "https://github.com/${GIT_FULL_REPO_NAME}.git",
                                            ]],
                                        ]
                                    )
                                }
                            }
                        }
                    }
                }
}
```
## Problem

take 5min13s in cache block waiting, and finally failed!

<img width="337" alt="image" src="https://user-images.githubusercontent.com/2574558/187362186-5e127f61-3e2b-4124-8c83-4659abf66e75.png">

## Jenkins build failure stacktrace

```java
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.Channel.call(Channel.java:999)
	at hudson.FilePath.act(FilePath.java:1194)
	at hudson.FilePath.act(FilePath.java:1183)
	at io.jenkins.plugins.pipeline.cache.CacheStep$CacheStepExecution$1.onSuccess(CacheStep.java:118)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:372)
	at com.cloudbees.groovy.cps.Outcome.resumeFrom(Outcome.java:73)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:166)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by wuhuizuo** [comment]
and not printed out `Cache saved successfully ***` log line.

**Comment by wuhuizuo** [comment]
@j3t help 🆘

**Comment by j3t** [comment]
Which version are you using? Is the issue reproducible?

**Comment by wuhuizuo** [comment]
Save the object timeout since the low bandwidth. the S3 backend problem.
